import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PageHeader from "@/components/organisms/PageHeader";
import PageFooter from "@/components/organisms/PageFooter"
import "@/assets/styles/global.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EarlyStudio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <PageHeader/>
          {children}
        <PageFooter />
      </body>
    </html>
  );
}
